

let countries = {

    "AD" : "Andorra",
    "AE": "دولة الإمارات العربية المتحدة",
    "AG": "Antigua & Barbuda",
    "AI": "Anguilla",
    "AL": "Shqipëri",
    "AM": "Հայաստան",
    "AO": "Angola", 
    "AR": "Argentina",
    "AS": "American Samoa",
    "AT": "Österreich",
    "AU": "Australia",
    "AW": "Aruba",
    "AX": "Landskapet Åland",
    "AZ": "Azərbaycan Respublikası",
    "BA": "Bosna i Hercegovina",
    "BB": "Barbados",
    "BD": "গণপ্রজাতন্ত্রী বাংলাদেশ",
    "BE": "Belgique",
    "BF": "Burkina Faso",
    "BG": "България",
    "BH": "مملكة البحرين",
    "BI": "République du Burundi",
    "BJ": "République du Bénin",
    "BL": "St. Barthélemy",
    "BM": "Bermuda",
    "BN": "Negara Brunei Darussalam",
    "BO": "Bolivia",
    "BQ": "Caribisch Nederland",
    "BR": "Brasil",
    "BS": "Bahamas",
    "BW": "Botswana",
    "BY": "Рэспубліка Беларусь",
    "BZ": "Belize",
    "CA": "Canada",
    "CC": "Cocos (Keeling) Islands",
    "CD": "République démocratique du Congo",
    "CF": "République centrafricaine",
    "CG": "République du Congo",
    "CH": "Schweiz",
    "CI": "République de Côte d'Ivoire",
    "CK": "Cook Islands",
    "CL": "Chile",
    "CM": "Cameroun",
    "CN": "中华人民共和国",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "República de Cabo Verde",
    "CW": "Curaçao",
    "CX": "Christmas Island",
    "CY": "Κύπρος",
    "CZ": "Česká republika",
    "DE": "Deutschland",
    "DJ": "République de Djibouti",
    "DK": "Danmark",
    "DM": "Dominica",
    "DO": "República Dominicana",
    "DZ": "ا<جمهورية الجزائرية الديمقراطية الشعبية",
    "EC": "Ecuador",
    "EE": "Eesti",
    "EG": "جمهورية مصر العربية",
    "EH": "الجمهورية العربية الصحراوية الديمقراطية",
    "ER": "Eritrea",
    "ES": "España",
    "ET": "ኢትዮጵያ",
    "FI": "Suomi",
    "FJ": "Matanitu Tugalala o Viti",
    "FO": "Føroyar",
    "FR": "France",
    "GA": "Gabon",
    "GB": "United Kingdom",
    "GD": "Grenada",
    "GE": "საქართველო",
    "GF": "Guyane",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Kalaallit Nunaat",
    "GM": "The Gambia",
    "GN": "Guinée",
    "GP": "Guadeloupe",
    "GQ": "República de Guinea Ecuatorial",
    "GR": "Ελλάδα",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guiné-Bissau",
    "GY": "Guyana",
    "HK": "香港",
    "HN": "Honduras",
    "HR": "Hrvatska",
    "HT": "Haïti",
    "HU": "Magyarország",
    "IC": "Islas Canarias",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IS": "Ísland",
    "IT": "Italia",
    "JE": "Jersey",
    "JM": "Jamaica",
    "JP": "日本",
    "KE": "Kenya",
    "KM": "Union des Comores",
    "KN": "St. Kitts & Nevis",
    "KR": "대한민국",
    "KY": "Cayman Islands",
    "LC": "St. Lucia",
    "LI": "Lichtenstein",
    "LR": "Liberia",
    "LS": "'Muso oa Lesotho",
    "LT": "Lietuva",
    "LU": "Luxembourg",
    "LV": "Latvija",
    "LY": "دولة ليبيا",
    "MA": "المملكة المغربية",
    "MC": "Monaco",
    "MD": "Republica Moldova",
    "ME": "Crna Gora",
    "MF": "Saint Martin",
    "MG": "Repoblikan'i Madagasikara",
    "MK": "Република Македонија",
    "ML": "République du Mali",
    "MQ": "Martinique",
    "MR": "الجمهورية الإسلامية الموريتانية",
    "MS": "Montserrat",
    "MT": "Malta",
    "MW": "Malawi",
    "MX": "México",
    "MY": "Malaysia",
    "MZ": "Moçambique",
    "NA": "Namibia",
    "NC": "Nouvelle-Calédonie",
    "NE": "République du Niger",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Nederland",
    "NO": "Norge",
    "NZ": "New Zealand",
    "PA": "Panamá",
    "PE": "Perú",
    "PH": "Philippines",
    "PL": "Polska",
    "PM": "St. Pierre & Miquelon",
    "PR": "Puerto Rico",
    "PT": "Portugal",
    "PY": "Paraguay",
    "RE": "Réunion",
    "RO": "Romania",
    "RS": "Република Србија",
    "RU": "Россия",
    "RW": "Rwanda",
    "SC": "Seychelles",
    "SD": "جمهورية السودان",
    "SE": "Sverige",
    "SG": "Singapore",
    "SH": "St. Helena",
    "SI": "Republika Slovenija",
    "SJ": "Svalbard & Jan Mayen",
    "SK": "Slovenská republika",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "République du Sénégal",
    "SO": "Jamhuuriyadda Federaalka Soomaaliya",
    "SR": "Suriname",
    "SS": "South Sudan",
    "ST": "São Tomé & Príncipe",
    "SV": "El Salvador",
    "SX": "Sint Maarten",
    "SZ": "Eswatini",
    "TC": "Turks & Caicos Islands",
    "TD": "جمهورية تشاد",
    "TG": "République togolaise",
    "TN": "الجمهورية التونسية",
    "TO": "Puleʻanga Fakatuʻi ʻo Tonga",
    "TR": "Türkiye",
    "TT": "Trinidad & Tobago",
    "TW": "中華民國",
    "TZ": "Tanzania",
    "UA": "Україна",
    "UG": "Uganda",
    "US": "United States of America",
    "UY": "Uruguay",
    "VA": "Stato della Città del Vaticano",
    "VC": "St. Vincent & Grenadines",
    "VE": "Venezuela",
    "VG": "British Virgin Islands",
    "VI": "U.S. Virgin Islands",
    "VN": "Cộng hòa Xã hội chủ nghĩa Việt Nam",
    "VU": "République de Vanuatu",
    "XK": "Republika e Kosovës",
    "YT": "Mayotte",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}


export default countries;