// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';


// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI'

export const SET_OPEN_TRUE = 'SET_OPEN_TRUE';
export const SET_OPEN_FALSE = 'SET_OPEN_FALSE';

export const SET_WORKING_OPEN_TRUE = 'SET_WORKING_OPEN_TRUE';
export const SET_WORKING_OPEN_FALSE = 'SET_WORKING_OPEN_FALSE';

export const LOADING_APPOINTMENTS = 'LOADING_APPOINTMENTS'
export const SET_APPOINTMENTS = 'SET_APPOINTMENTS';
export const SET_APPOINTMENT_ID = 'SET_APPOINTMENT_ID'
export const SET_APPOINTMENT_ID_NULL = 'SET_APPOINTMENT_ID_NULL'

// dashboard
export const DASHBOARD_HOME = 'DASHBOARD_HOME'
export const DASHBOARD_APPOINTMENT = 'DASHBOARD_APPOINTMENT';
export const DASHBOARD_PATIENTS = 'DASHBOARD_PATIENTS'
export const DASHBOARD_PROFILE = 'DASHBOARD_PROFILE'
export const DASHBOARD_USERS = 'DASHBOARD_USERS'
export const DASHBOARD_PROFESSIONALS = 'DASHBOARD_PROFESSIONALS'

export const SET_WORKING_TIME_M = 'SET_WORKING_TIME_M';
export const SET_WORKING_TIME_T = 'SET_WORKING_TIME_T';
export const SET_WORKING_TIME_W = 'SET_WORKING_TIME_W';
export const SET_WORKING_TIME_TR = 'SET_WORKING_TIME_TR';
export const SET_WORKING_TIME_F = 'SET_WORKING_TIME_F';
export const SET_WORKING_TIME_SA = 'SET_WORKING_TIME_SA';
export const SET_WORKING_TIME_SU = 'SET_WORKING_TIME_SU';

export const SET_EARLIEST_DAY = 'SET_EARLIEST_DAY';
export const SET_RULE = 'SET_RULE';
export const SET_HOLIDAYS = 'SET_HOLIDAYS';
export const SET_RESERVE_TIME = 'SET_RESERVE_TIME';

export const SET_WORK_ZERO = 'SET_WORK_ZERO';
export const SET_LOADING_UPDATE_WORK_TRUE = 'SET_LOADING_UPDATE_WORK_TRUE';
export const SET_LOADING_UPDATE_WORK_FALSE = 'SET_LOADING_UPDATE_WORK_FALSE'

export const SET_CANCEL_LOADING_TRUE= 'SET_CANCEL_LOADING_TRUE';
export const SET_CANCEL_LOADING_FALSE= 'SET_CANCEL_LOADING_FALSE';

export const REMOVE_APPOINTMENT = 'REMOVE_APPOINTMENT';
export const UPDATE_TIME_HWER = 'UPDATE_TIME_HWER'

export const ADD_DOCTOR_TO_LIST = 'ADD_DOCTOR_TO_LIST'

export const ADD_PROF_TRUE = 'ADD_PROF_TRUE'
export const ADD_PROF_FALSE = 'ADD_PROF_FALSE'

export const SET_RESERVE_WINDOW_TRUE = 'SET_RESERVE_WINDOW_TRUE';
export const SET_RESERVE_WINDOW_FALSE = 'SET_RESERVE_WINDOW_FALSE';

export const LOADING_RESERVE_TRUE = 'LOADING_RESERVE_TRUE';
export const LOADING_RESERVE_FALSE = 'LOADING_RESERVE_FALSE';

export const SET_RESERVED_TIME = 'SET_RESERVED_TIME';

export const REMOVE_RESERVED_TIME = 'REMOVE_RESERVED_TIME';

export const SET_REMOVE_LOADING_TRUE = 'SET_REMOVE_LOADING_TRUE';
export const SET_REMOVE_LOADING_FALSE = 'SET_REMOVE_LOADING_FALSE';

export const OPEN_ADD_USER_BOX = 'OPEN_ADD_USER_BOX';
export const CLOSE_ADD_USER_BOX = 'CLOSE_ADD_USER_BOX';

export const ADD_USER_TO_STATE = 'ADD_USER_TO_STATE';

export const CLEAR_STATE_NEW_USER_FALSE = 'CLEAR_STATE_NEW_USER_FALSE'
export const CLEAR_STATE_NEW_USER_TRUE = 'CLEAR_STATE_NEW_USER_TRUE'

export const LOADING_ADD_APP_TRUE = 'LOADING_ADD_APP_TRUE';
export const LOADING_ADD_APP_FALSE = 'LOADING_ADD_APP_FALSE';

export const ADD_APPOINTMENT = 'ADD_APPOINTMENT';

export const OPEN_CALENDAR_ADD_APP = 'OPEN_CALENDAR_ADD_APP';
export const CLOSE_CALENDAR_ADD_APP = 'CLOSE_CALENDAR_ADD_APP';

export const SET_AVAILABLE_SLOTS = 'SET_AVAILABLE_SLOTS';
export const CLEAR_AVAILABLE_SLOTS = 'CLEAR_AVAILABLE_SLOTS'

export const SET_SELECTED_TIME_SLOT = 'SET_SELECTED_TIME_SLOT'
export const CLEAR_SELECTED_TIME_SLOT = 'CLEAR_SELECTED_TIME_SLOT'

export const OPEN_SCHEDULE_DIALOG = 'OPEN_SCHEDULE_DIALOG';
export const CLOSE_SCHEDULE_DIALOG = 'CLOSE_SCHEDULE_DIALOG'

export const LOADING_SCHEDULE_APP_TRUE = 'LOADING_SCHEDULE_APP_TRUE';
export const LOADING_SCHEDULE_APP_FALSE = 'LOADING_SCHEDULE_APP_FALSE';




